[package]
name = "bdk_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk_wallet = { path = "/home/amos/Desktop/bdk/crates/wallet", features = ["keys-bip39"] }
rand = "0.8"
bitcoin = "0.29"
secp256k1 = { version = "0.29", features = ["global-context"] }
serde_json = "1.0"
serde = "1.0"



